url: https://juliepedeville.github.io
baseurl:

# Site settings
title: Julie Pédeville
email: pedeville.julie@gmail.com
description: "Site web personnel de Julie Pédeville - Project Manager en Marketing Digital"

linkedin: https://www.linkedin.com/in/julie-pédeville-36747092

# Build settings
markdown: kramdown
permalink: pretty